# Generated by Django 3.0.5 on 2020-08-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='personal_portfolio/images/')),
                ('description', models.TextField(max_length=300)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
