# Generated by Django 3.0.5 on 2020-08-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personal_portfolio',
            new_name='Project',
        ),
    ]
